branch-defaults:
  main:
    environment: django-env-12
    group_suffix: null
environment-defaults:
  django-env-12:
    branch: null
    repository: null
  django-env-5:
    branch: null
    repository: null
  django-env1:
    branch: null
    repository: null
global:
  application_name: django-tutorial-12
  branch: null
  default_ec2_keyname: team1key
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
